name: Poetrel
description: Github Action for automatic releases with Poetry

inputs:
  changelog:
    description: The path to the Changelog file
    required: true
  commit-prefix:
    description: The message to display before the version in the commit message
    required: false
    default: '[skip actions] Release '
  github-token:
    description: The repository token (secrets.GITHUB_TOKEN)
    required: true
  pypi-token:
    description: The PyPI API token if you want to publish to PyPI
    required: false
  setup-poetry:
    description: Whether Poetrel should setup Python and Poetry
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Get pull request label
      id: get-label
      uses: corentin-regent/poetrel/get-label@v1
      with:
        github-token: ${{ inputs.github-token }}

    - name: Save release notes
      uses: corentin-regent/poetrel/save-notes@v1
      with:
        changelog: ${{ inputs.changelog }}
        notes-file: .notes.txt

    - name: Setup Python
      if: ${{ inputs.setup-poetry == 'true' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      if: ${{ inputs.setup-poetry == 'true' }}
      uses: snok/install-poetry@v1

    - name: Bump project version
      if: ${{ steps.get-label.outputs.action != 'no-bump' }}
      shell: bash
      run: poetry version "${{ steps.get-label.outputs.action }}"

    - name: Get new project version
      id: get-version
      shell: bash
      run: echo "new-version=$(poetry version -s)" >> $GITHUB_OUTPUT

    - name: Write new version to Changelog
      uses: corentin-regent/poetrel/write-version@v1
      with:
        changelog: ${{ inputs.changelog }}
        version: ${{ steps.get-version.outputs.new-version }}

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ inputs.commit-prefix }}${{ steps.get-version.outputs.new-version }}
        file_pattern: ${{ inputs.changelog }} pyproject.toml

    - name: Publish to PyPI
      if: inputs.pypi-token
      shell: bash
      run: |
        poetry config pypi-token.pypi "${{ inputs.pypi-token }}"
        poetry publish --build --no-interaction

    - name: Create a GitHub release
      uses: corentin-regent/poetrel/release@v1
      with:
        version: ${{ steps.get-version.outputs.new-version }}
        notes-file: .notes.txt
        github-token: ${{ inputs.github-token }}

branding:
  icon: chevrons-up
  color: blue
