name: Synchronize Poetrel labels
description: Synchronize the GitHub labels to add the ones from Poetrel

inputs:
  github-token:
    description: The repository token (secrets.GITHUB_TOKEN)
    required: true
  setup-python:
    description: Whether Poetrel should setup Python
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Python
      if: ${{ inputs.setup-python == 'true' }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install labels
      shell: bash
      run: pip install labels

    - name: Sync labels with GitHub
      shell: bash
      run: labels -u ${{ inputs.owner }} -t ${{ input.github-token }} sync -f .github/labels.toml
