name: Synchronize Poetrel labels
description: Synchronize the GitHub labels to add the ones from Poetrel

inputs:
  github-token:
    description: The repository token (secrets.GITHUB_TOKEN)
    required: true
  owner:
    description: The owner of your repository
    required: true
  setup-python:
    description: Whether Poetrel should setup Python
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Python
      if: ${{ inputs.setup-python == 'true' }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install labels
      shell: bash
      run: pip install labels

    - name: Fetch Poetrel labels file
      shell: bash
      run: # TODO: use main branch
        curl https://raw.githubusercontent.com/corentin-regent/poetrel/develop/.github/labels.toml
        -o .poetrel_labels.toml

    - name: Sync labels with GitHub
      shell: bash
      run:
        labels sync -u github-actions[bot] -o ${{ inputs.owner }} -t ${{ inputs.github-token }} -f
        .poetrel_labels.toml
