name: Release
description: Create a GitHub Release

inputs:
  github-token:
    description: GitHub token used to create the release
    default: ${{ github.token }}
    required: false
  notes-file:
    description: The path to the release notes file
    required: true
  version:
    description: The version to release
    required: true

runs:
  using: composite
  steps:
    - name: Create a GitHub release
      shell: bash
      run: |
        mk_release='gh release create v${{ inputs.version }} --title v${{ inputs.version }} --notes-file ${{ inputs.notes-file }}'
        if [[ '${{ inputs.version }}' =~ [a-z] ]]; then
          $mk_release --prerelease
        else
          $mk_release
        fi
      env:
        GH_TOKEN: ${{ inputs.github-token }}
