name: Get label
description: Extract the label of the pull request, if any matches

inputs:
  github-token:
    description: GitHub token used to read the labels from the PR that the commit originated from
    default: ${{ github.token }}
    required: false

outputs:
  action:
    description: The Poetry action specified by the PR label

runs:
  using: node20
  main: ../dist/get-label/index.js
