name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Get pull request label
        id: get-label
        uses: corentin-regent/poetrel/get-label@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Setup Git
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump the project version
        shell: bash
        run: npm version ${{ steps.get-label.outputs.action }} -m "[skip ci] Bump to %s"

      - name: Push version change
        shell: bash
        run: git push

      - name: Push new tag
        shell: bash
        run: git push --tags

      - name: Release the GitHub Action
        uses: ./release-gh-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
