name: Continuous Integration

on:
  pull_request:
    paths:
      - '**.ts'
      - 'package.json'
      - 'package.lock'
      - 'scripts/package.sh'
      - '.github/workflows/ci.yml'
      - '.eslintignore'
      - '.eslintrc.yml'
      - '.prettierignore'
      - '.prettierrc.json'
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run formatter
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[skip actions] Format codebase'

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Cleanup dist/
        run: rm -rf dist/

      - name: Build dist/
        run: npm run package

      - name: Commit dist/
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[skip actions] Build dist/'
          file_pattern: dist/**

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test
