name: Synchronize Poetrel labels

on:
  schedule:
    - cron: '0 0 * * *' # once a day

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Sync labels with GitHub
        uses: ./sync-labels
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
