name: Synchronize labels

on:
  push:
    paths:
      - '.github/workflows/labels.yml'
      - 'sync-labels/**'

jobs:
  sync:
    name: Synchronize labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Sync labels with GitHub
        uses: ./sync-labels
